name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build inside dev container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            cmake --preset debug
            cmake --build --preset debug
            ctest --preset debug

            cmake --preset aarch64-debug
            cmake --build --preset aarch64-debug

            cmake --preset release
            cmake --build --preset release
            ctest --preset release

            cmake --preset relwithdebinfo
            cmake --build --preset relwithdebinfo
            ctest --preset relwithdebinfo
